In [31]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [32]:
books = pd.read_csv('data\BX-Books.csv', sep=';', on_bad_lines='skip', encoding='latin-1', usecols=['ISBN','Book-Title','Book-Author','Year-Of-Publication','Publisher','Image-URL-L'])
books.head()

<>:1: SyntaxWarning: invalid escape sequence '\B'
<>:1: SyntaxWarning: invalid escape sequence '\B'
C:\Users\namde\AppData\Local\Temp\ipykernel_9748\140641597.py:1: SyntaxWarning: invalid escape sequence '\B'
  books = pd.read_csv('data\BX-Books.csv', sep=';', on_bad_lines='skip', encoding='latin-1', usecols=['ISBN','Book-Title','Book-Author','Year-Of-Publication','Publisher','Image-URL-L'])
C:\Users\namde\AppData\Local\Temp\ipykernel_9748\140641597.py:1: DtypeWarning: Columns (0: Year-Of-Publication) have mixed types. Specify dtype option on import or set low_memory=False.
  books = pd.read_csv('data\BX-Books.csv', sep=';', on_bad_lines='skip', encoding='latin-1', usecols=['ISBN','Book-Title','Book-Author','Year-Of-Publication','Publisher','Image-URL-L'])

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...

In [33]:
books.shape

(271379, 6)

In [34]:
books.columns

Index(['ISBN', 'Book-Title', 'Book-Author', 'Year-Of-Publication', 'Publisher',
       'Image-URL-L'],
      dtype='str')

In [35]:
books.rename(columns = {
    'Book-Title':'Title',
    'Book-Author':'Author',
    'Year-Of-Publication':'Year',
    'Image-URL-L':'img_url'
}, inplace=True)

In [36]:
users = pd.read_csv('data\BX-Users.csv', sep=';', on_bad_lines='skip', encoding='latin-1')
users.head()

<>:1: SyntaxWarning: invalid escape sequence '\B'
<>:1: SyntaxWarning: invalid escape sequence '\B'
C:\Users\namde\AppData\Local\Temp\ipykernel_9748\773095986.py:1: SyntaxWarning: invalid escape sequence '\B'
  users = pd.read_csv('data\BX-Users.csv', sep=';', on_bad_lines='skip', encoding='latin-1')

   User-ID                            Location   Age
0        1                  nyc, new york, usa   NaN
1        2           stockton, california, usa  18.0
2        3     moscow, yukon territory, russia   NaN
3        4           porto, v.n.gaia, portugal  17.0
4        5  farnborough, hants, united kingdom   NaN

In [37]:
users.shape

(278858, 3)

In [38]:
ratings = pd.read_csv('data\BX-Book-Ratings.csv', sep=';', on_bad_lines='skip', encoding='latin-1')
ratings.head()

<>:1: SyntaxWarning: invalid escape sequence '\B'
<>:1: SyntaxWarning: invalid escape sequence '\B'
C:\Users\namde\AppData\Local\Temp\ipykernel_9748\1946914896.py:1: SyntaxWarning: invalid escape sequence '\B'
  ratings = pd.read_csv('data\BX-Book-Ratings.csv', sep=';', on_bad_lines='skip', encoding='latin-1')

   User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726  0155061224            5
2   276727  0446520802            0
3   276729  052165615X            3
4   276729  0521795028            6