In [151]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [152]:
books = pd.read_csv('data\BX-Books.csv', sep=';', on_bad_lines='skip', encoding='latin-1', usecols=['ISBN','Book-Title','Book-Author','Year-Of-Publication','Publisher','Image-URL-L'])
books.head()

<>:1: SyntaxWarning: invalid escape sequence '\B'
<>:1: SyntaxWarning: invalid escape sequence '\B'
C:\Users\namde\AppData\Local\Temp\ipykernel_4724\140641597.py:1: SyntaxWarning: invalid escape sequence '\B'
  books = pd.read_csv('data\BX-Books.csv', sep=';', on_bad_lines='skip', encoding='latin-1', usecols=['ISBN','Book-Title','Book-Author','Year-Of-Publication','Publisher','Image-URL-L'])
C:\Users\namde\AppData\Local\Temp\ipykernel_4724\140641597.py:1: DtypeWarning: Columns (0: Year-Of-Publication) have mixed types. Specify dtype option on import or set low_memory=False.
  books = pd.read_csv('data\BX-Books.csv', sep=';', on_bad_lines='skip', encoding='latin-1', usecols=['ISBN','Book-Title','Book-Author','Year-Of-Publication','Publisher','Image-URL-L'])

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...

In [153]:
books.columns

Index(['ISBN', 'Book-Title', 'Book-Author', 'Year-Of-Publication', 'Publisher',
       'Image-URL-L'],
      dtype='str')

In [154]:
books.rename(columns = {
    'Book-Title':'title',
    'Book-Author':'author',
    'Year-Of-Publication':'year',
    'Image-URL-L':'img_url'
}, inplace=True)

In [155]:
users = pd.read_csv('data\BX-Users.csv', sep=';', on_bad_lines='skip', encoding='latin-1')
users.head()

<>:1: SyntaxWarning: invalid escape sequence '\B'
<>:1: SyntaxWarning: invalid escape sequence '\B'
C:\Users\namde\AppData\Local\Temp\ipykernel_4724\773095986.py:1: SyntaxWarning: invalid escape sequence '\B'
  users = pd.read_csv('data\BX-Users.csv', sep=';', on_bad_lines='skip', encoding='latin-1')

   User-ID                            Location   Age
0        1                  nyc, new york, usa   NaN
1        2           stockton, california, usa  18.0
2        3     moscow, yukon territory, russia   NaN
3        4           porto, v.n.gaia, portugal  17.0
4        5  farnborough, hants, united kingdom   NaN

In [156]:
ratings = pd.read_csv('data\BX-Book-Ratings.csv', sep=';', on_bad_lines='skip', encoding='latin-1')
ratings.head()

<>:1: SyntaxWarning: invalid escape sequence '\B'
<>:1: SyntaxWarning: invalid escape sequence '\B'
C:\Users\namde\AppData\Local\Temp\ipykernel_4724\1946914896.py:1: SyntaxWarning: invalid escape sequence '\B'
  ratings = pd.read_csv('data\BX-Book-Ratings.csv', sep=';', on_bad_lines='skip', encoding='latin-1')

   User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726  0155061224            5
2   276727  0446520802            0
3   276729  052165615X            3
4   276729  0521795028            6

In [157]:
print(books.shape)
print(users.shape)
print(ratings.shape)

(271379, 6)
(278858, 3)
(1149780, 3)

In [158]:
ratings.rename(columns={
    'User-ID':'user_id',
    'Book-Rating':'rating'
}, inplace=True)

In [159]:
ratings.head()

   user_id        ISBN  rating
0   276725  034545104X       0
1   276726  0155061224       5
2   276727  0446520802       0
3   276729  052165615X       3
4   276729  0521795028       6

In [160]:
users.rename(columns={
    'User-ID':'user_id',
    'Location':'location',
    'Age':'age'
},inplace=True)

In [161]:
ratings['user_id'].value_counts()

user_id
11676     13602
198711     7550
153662     6109
98391      5891
35859      5850
          ...
276697        1
276706        1
276709        1
276721        1
276723        1
Name: count, Length: 105283, dtype: int64

In [162]:
ratings['user_id'].nunique()

105283

In [163]:
ratings.shape

(1149780, 3)

In [164]:
# Users who have rated at least 200 books (1200)

user_counts = ratings['user_id'].value_counts()
filtered_users = user_counts[user_counts >= 200].index
ratings = ratings[ratings['user_id'].isin(filtered_users)]
ratings

         user_id        ISBN  rating
1456      277427  002542730X      10
1457      277427  0026217457       0
1458      277427  003008685X       8
1459      277427  0030615321       0
1460      277427  0060002050       0
...          ...         ...     ...
1147612   275970  3829021860       0
1147613   275970  4770019572       0
1147614   275970   896086097       0
1147615   275970  9626340762       8
1147616   275970  9626344990       0

[527556 rows x 3 columns]

In [165]:
books.shape

(271379, 6)

In [166]:
books.head(3)

,ISBN,title,author,year,Publisher,img_url
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...

In [167]:
# Merging the books and ratings dataframe with the common column 'ISBN' so we get books with more than 200 ratings
ratings_with_books = ratings.merge(books, on='ISBN')
ratings_with_books.shape

(488756, 8)

In [168]:
ratings_with_books.head(3)

,user_id,ISBN,rating,title,author,year,Publisher,img_url
0,277427,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,http://images.amazon.com/images/P/002542730X.0...
1,277427,0026217457,0,Vegetarian Times Complete Cookbook,Lucy Moll,1995,John Wiley &amp; Sons,http://images.amazon.com/images/P/0026217457.0...
2,277427,003008685X,8,Pioneers,James Fenimore Cooper,1974,Thomson Learning,http://images.amazon.com/images/P/003008685X.0...

In [169]:
ratings_with_books['title'].value_counts()

title
Wild Animus                                                                                               365
Bridget Jones's Diary                                                                                     278
The Lovely Bones: A Novel                                                                                 272
The Notebook                                                                                              242
The Pelican Brief                                                                                         236
                                                                                                         ...
Here Is New York                                                                                            1
There's a Porcupine in My Outhouse: Misadventures of a Mountain Man Wannabe (Capital Discoveries Book)      1
Die Biene.                                                                                                  1
The Penis Book                                                                                              1
Musashi                                                                                                     1
Name: count, Length: 160587, dtype: int64

In [170]:
# Counts how many ratings each book has received and returns it as a clean DataFrame with title and rating columns
num_ratings = ratings_with_books.groupby('title')['rating'].count().reset_index()
num_ratings.head(3)

                                               title  rating
0   A Light in the Storm: The Civil War Diary of ...       2
1                              Always Have Popsicles       1
2               Apple Magic (The Collector's series)       1

In [171]:
num_ratings.rename(columns={'rating':'no_of_rating'},inplace=True)
num_ratings.head(3)

                                               title  no_of_rating
0   A Light in the Storm: The Civil War Diary of ...             2
1                              Always Have Popsicles             1
2               Apple Magic (The Collector's series)             1

In [172]:
# merging the ratings_with_books and num_ratings dataframes
final_rating = ratings_with_books.merge(num_ratings, on='title')
final_rating.head(3)

,user_id,ISBN,rating,title,author,year,Publisher,img_url,no_of_rating
0,277427,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,http://images.amazon.com/images/P/002542730X.0...,82
1,277427,0026217457,0,Vegetarian Times Complete Cookbook,Lucy Moll,1995,John Wiley &amp; Sons,http://images.amazon.com/images/P/0026217457.0...,7
2,277427,003008685X,8,Pioneers,James Fenimore Cooper,1974,Thomson Learning,http://images.amazon.com/images/P/003008685X.0...,1

In [173]:
final_rating.shape

(488756, 9)

In [174]:
final_rating = final_rating[final_rating['no_of_rating'] >= 50]
final_rating.shape

(62149, 9)

In [175]:
final_rating.sample(7)

,user_id,ISBN,rating,title,author,year,Publisher,img_url,no_of_rating
477171,268110,0425184943,6,Blue Diary,Alice Hoffman,2002,Berkley Publishing Group,http://images.amazon.com/images/P/0425184943.0...,67
174715,98758,074343627X,0,Dreamcatcher,Stephen King,2001,Pocket,http://images.amazon.com/images/P/074343627X.0...,162
210428,123883,0373218540,5,Dangerous,Nora Roberts,2002,Silhouette,http://images.amazon.com/images/P/0373218540.0...,57
435336,244349,0440222656,0,The Horse Whisperer,Nicholas Evans,1996,Dell,http://images.amazon.com/images/P/0440222656.0...,213
180800,102967,0425145638,0,Fatal Cure,Robin Cook,1997,Berkley Publishing Group,http://images.amazon.com/images/P/0425145638.0...,60
36539,16795,0684874350,7,ANGELA'S ASHES,Frank McCourt,1996,Scribner,http://images.amazon.com/images/P/0684874350.0...,81
335013,195694,0425107469,0,Watchers,Dean R. Koontz,1996,Berkley Publishing Group,http://images.amazon.com/images/P/0425107469.0...,71

In [181]:
print(final_rating.duplicated().sum())
print(final_rating.isna().sum())

0
user_id         0
ISBN            0
rating          0
title           0
author          0
year            0
Publisher       0
img_url         0
no_of_rating    0
dtype: int64

In [182]:
final_rating.drop_duplicates(['user_id','title'],inplace=True)

In [183]:
final_rating.shape

(60141, 9)

In [184]:
final_rating.info()

<class 'pandas.DataFrame'>
Index: 60141 entries, 0 to 488704
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   user_id       60141 non-null  int64
 1   ISBN          60141 non-null  str
 2   rating        60141 non-null  int64
 3   title         60141 non-null  str
 4   author        60141 non-null  str
 5   year          60141 non-null  object
 6   Publisher     60141 non-null  str
 7   img_url       60141 non-null  str
 8   no_of_rating  60141 non-null  int64
dtypes: int64(3), object(1), str(5)
memory usage: 11.5+ MB

In [186]:
book_pivot = final_rating.pivot_table(index='title',columns='user_id',values='rating')
book_pivot

user_id,254,2276,2766,2977,3363,3757,4017,4385,6242,6251,...,274004,274061,274301,274308,274808,275970,277427,277478,277639,278418
title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
1st to Die: A Novel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2nd Chance,NaN,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN
4 Blondes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84 Charing Cross Road,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,10.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Year of Wonders,NaN,NaN,NaN,7.0,NaN,NaN,NaN,NaN,7.0,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
You Belong To Me,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
Zoya,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"\O\"" Is for Outlaw""",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [187]:
book_pivot.fillna(0,inplace=True)
book_pivot

user_id,254,2276,2766,2977,3363,3757,4017,4385,6242,6251,...,274004,274061,274301,274308,274808,275970,277427,277478,277639,278418
title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1st to Die: A Novel,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2nd Chance,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4 Blondes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
84 Charing Cross Road,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,10.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Year of Wonders,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,7.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
You Belong To Me,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zoya,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"\O\"" Is for Outlaw""",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [188]:
from scipy.sparse import csr_matrix

In [189]:
book_sparse = csr_matrix(book_pivot)
book_sparse

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 15059 stored elements and shape (746, 894)>

# Modeling

In [190]:
from sklearn.neighbors import NearestNeighbors
model = NearestNeighbors(algorithm='brute')

model.fit(book_sparse)

NearestNeighbors(algorithm='brute')

In [ ]:
distance, suggestion =